# Package management
abbr packagesort 'npx sort-package-json'

# Bazel shortcuts
abbr bz 'bazel'
abbr bb 'bazel build'
abbr bt 'bazel test'
abbr br 'bazel run'

# Webdev
abbr pns 'pnpm start'
abbr pnl 'pnpm lint'
abbr pnlf 'pnpm lint --fix'
abbr pnb 'pnpm build'
abbr pni 'pnpm install'
abbr pnd 'pnpm dev'
abbr pnff 'pnpm --filter'
abbr gittree 'tree --gitignore > tree.txt'
abbr ngd 'ngrok http --domain=good-panda-smooth.ngrok-free.app'

# Python
abbr ipy 'ipython'
abbr pfr 'pip freeze > requirements.txt'
abbr pi 'pip install'
abbr pig 'sudo pip install'
abbr pir 'pip install -r requirements.txt'
abbr py 'python -B'
abbr va 'source .venv/bin/activate'
abbr vd 'deactivate'
abbr vm 'python -m venv .venv'

# NPM
abbr n 'npm'
abbr nb 'npm run build'
abbr ni 'npm install'
abbr nie 'npm install --save-exact'
abbr nig 'npm install -g'
abbr nis 'npm install --save'
abbr nisd 'npm install --save-dev'
abbr nl 'npm run lint'
abbr nr 'npm run'
abbr nrc 'npm run compile'
abbr ncw 'npm run compile:watch'
abbr nd 'npm run dev'
abbr nn 'NODE_ENV=development node'
abbr nnn 'NODE_ENV=development node -r dotenv-flow/config'
abbr ns 'npm start'
abbr nsw 'npm run start:watch'
abbr nt 'npm test'
abbr nu 'npm uninstall'
abbr nv 'npm run coverage'
abbr ntw 'npm run test:watch'
abbr nll 'npm ls --depth=0 --link=true'

# Yarn
abbr y 'yarn'
abbr yd 'yarn dev'

# Forge/Hardhat
abbr fb 'forge build'
abbr ft 'forge test'
abbr hh 'hardhat'
abbr hhc 'hardhat compile'
abbr hhn 'hardhat console'
abbr hhr 'hardhat run'
abbr hht 'hardhat test'
abbr hhb 'hardhat --network mumbai'
abbr hhbn 'hardhat --network mumbai console'
abbr hhm 'hardhat --network mainnet'
abbr hhmn 'hardhat --network mainnet console'
abbr hhp 'hardhat --network polygon'
abbr hhpn 'hardhat --network polygon console'

# Git
abbr g 'git'
abbr ga 'git add'
abbr gb 'git branch'
abbr gbb 'git branch --sort=committerdate'
abbr gbd 'git branch -D'
abbr gbl 'git for-each-ref --sort=authordate --format "%(authordate:iso) %(align:left,25)%(refname:short)%(end) %(subject)" refs/heads'
abbr gc 'git commit -v'
abbr gca 'git commit -v -a'
abbr gcm 'git commit -v -m'
abbr gcam 'git commit -v -a -m'
abbr gcamw 'git commit -v -a -m "wip"'
abbr gcan 'git commit -v --amend --no-edit'
abbr gcaa 'git commit -v -a --amend'
abbr gcaan 'git commit -v -a --amend --no-edit'
abbr gco 'git checkout'
abbr gcob 'git checkout -b'
abbr gcom 'git checkout main'
abbr gch 'git cherry'
abbr gchm 'git cherry main'
abbr gcp 'git cherry-pick'
abbr gcpa 'git cherry-pick --abort'
abbr gcpc 'git cherry-pick --continue'
abbr gd 'git diff'
abbr gdc 'git diff --cached'
abbr gdm 'git diff main'
abbr gfa 'git fetch --all'
abbr gfm 'git fetch origin main'
abbr gst 'git stash'
abbr gstd 'git stash drop'
abbr gstp 'git stash pop'
abbr gstw 'git stash show -p stash@{0}'
abbr gl 'git pull'
abbr glr 'git pull --rebase'
abbr gla 'git log --pretty=oneline HEAD^..HEAD | cut -c 1-7'
abbr glo 'git log --oneline --format="%h %<(50,trunc)%s" | less -R'
abbr gma 'git merge --abort'
abbr gmc 'git merge --continue'
abbr gmm 'git merge main'
abbr gn 'git clone'
abbr gp 'git push'
abbr gpf 'git push -f'
abbr gpu 'git push -u origin (git rev-parse --abbrev-ref HEAD)'
abbr gr 'git rebase'
abbr gra 'git rebase --abort'
abbr grc 'git rebase --continue'
abbr gri 'git rebase -i'
abbr gri2 'git rebase -i HEAD~2'
abbr gri3 'git rebase -i HEAD~3'
abbr gri4 'git rebase -i HEAD~4'
abbr gri5 'git rebase -i HEAD~5'
abbr grim 'git rebase -i main'
abbr grom 'git rebase origin/main'
abbr grm 'git rebase main'
abbr gru 'git fetch upstream; git rebase upstream/main'
abbr gs 'git status'
abbr gw 'git show'
abbr gsps 'git show --pretty=short --show-signature'
abbr gu 'git reset HEAD'
abbr guh 'git reset HEAD --hard'
abbr guu 'git reset HEAD^'
abbr guuh 'git reset HEAD^ --hard'

# GitHub CLI
abbr gcopr 'gh pr checkout'
abbr gpc 'gh pr create'
abbr gpm 'gh pr merge'

# Kubernetes
abbr k 'kubectl'
abbr gcal 'gcloud components update; and gcloud auth login --update-adc'
abbr kns 'kubens'
abbr kc 'kubectx'
abbr kgp 'kubectl get pods'

# Misc
abbr make 'gmake'
abbr glci 'golangci-lint run --fix'
abbr python 'python3'

# GCP Project Management
abbr gcadl 'gcloud auth application-default login'
abbr gcps 'gcloud config set project'
abbr gcpsprd 'gcloud config set project infinite-production-446115'
abbr gcpsdbx 'gcloud config set project infinite-sandbox-456108'
abbr gcpgp 'gcloud config get-value project'
